'use strict';
const fs=require('fs');
const assert=require('assert');
const cp=require('child_process');
const view=fs.readFileSync('js/endgame-mermaid-topology-r2.js','utf8');
const css=fs.readFileSync('css/endgame-mermaid-topology-r2.css','utf8');
const loader=fs.readFileSync('js/endgame-20260823.js','utf8');
const data=JSON.parse(fs.readFileSync('data/endgame-adjudication-v1.json','utf8'));

cp.execFileSync(process.execPath,['--check','js/endgame-mermaid-topology-r2.js'],{stdio:'pipe'});
assert.match(view,/flowchart TB/,'topology should stack claim swimlanes vertically');
assert.match(view,/direction LR/,'each claim lane should read left to right');
assert.match(view,/HOW TO READ THE MAP/,'graph needs an explicit topology legend');
assert.match(view,/THREE SEPARATE HORMUZ TESTS/,'Hormuz must visibly fork into separate dimensions');
assert.match(view,/MOU_STATUS'\?'expired'/,'expired MoU stages need a distinct semantic class');
assert.match(view,/LATER_COUNTERPARTY_POSITION:'counterparty'/,'counterparty movement must be mapped as a transition');
assert.match(view,/OBSERVABLE_IMPLEMENTATION:'observable test'/,'observable implementation must be mapped as a transition');
assert.match(view,/showAll=true/,'initial graph should present the whole strategic topology');
assert.match(view,/securityLevel:'strict'/,'Mermaid must remain strict-security');
assert.match(view,/htmlLabels:false/,'arbitrary HTML labels must remain disabled');
assert.match(view,/structured-adjudication-topology-r2/,'rendered graph needs an explicit structured-data provenance marker');
assert.match(view,/window\.ISREndgameAdjudicationR1\?\.pick/,'topology nodes must route selection through the authoritative R1 controller');
assert.match(css,/\.cluster rect/,'R2 must override Mermaid default cluster presentation');
assert.match(css,/eg-r2-cluster-active/,'selected swimlane needs a visual focus state');
assert.match(css,/eg-r2-cluster-dim/,'unselected swimlanes need a de-emphasis state');
assert.match(loader,/endgame-mermaid-topology-r2\.css/,'R2 topology stylesheet must be locally loaded');
assert.match(loader,/endgame-mermaid-topology-r2\.js/,'R2 topology renderer must be locally loaded');
assert.equal(data.claims.length,8,'all eight original victory-condition paths must remain mapped');
const hormuz=data.claims.find(c=>c.id==='hormuz');
assert.equal(hormuz.dimensions.length,3,'Hormuz must remain three-dimensional');
for(const display of Object.values(data.terminal_state_labels))assert(!view.includes(display),'terminal display verdicts must come from structured data, not duplicated JS prose');
console.log('endgame-topology-r2: swimlane topology, Hormuz fork, strict Mermaid and controller linkage passed');
