'use strict';
const assert = require('node:assert/strict');
const presentation = require('../js/presentation.js');

assert.equal(presentation.formatLabel('REPORTED_NOT_INDEPENDENTLY_VERIFIED'), 'UNCONTESTED');
assert.equal(presentation.formatLabel('SOURCE_REPORTED_NOT_INDEPENDENTLY_VERIFIED'), 'UNCONTESTED');
assert.equal(presentation.formatLabel('UNVERIFIED'), 'UNCONTESTED');
assert.equal(presentation.formatLabel('Source Reported Not Independently Verified'), 'UNCONTESTED');
assert.equal(presentation.evidenceState('SOURCE_REPORTED_NOT_INDEPENDENTLY_VERIFIED'), 'unverified');
assert.equal(presentation.evidenceLabel('SOURCE_REPORTED_NOT_INDEPENDENTLY_VERIFIED'), 'UNCONTESTED');
assert.equal(presentation.evidenceState('UNCONTESTED'), 'unverified');
assert.equal(presentation.evidenceLabel('UNCONTESTED'), 'UNCONTESTED');
assert.equal(presentation.evidenceState('CONTESTED'), 'contested');
assert.equal(presentation.evidenceState('HIGH — satellite imagery'), 'verified');
assert.equal(presentation.evidenceState('NOVEL_MACHINE_TOKEN'), 'neutral');
assert.equal(presentation.evidenceLabel('NOVEL_MACHINE_TOKEN'), 'UNRESOLVED');
assert.equal(presentation.physicalState('Combined Air Operations Center rendered inoperable.'), 'lost');
assert.equal(presentation.physicalState('Terminal 4 flights resumed and continued.'), 'operational');
assert.equal(presentation.physicalState('Campaign directed from Shaw AFB from the start.'), 'operational');
assert.equal(presentation.physicalState('Damage status unresolved.'), 'neutral');
assert.equal(presentation.physicalState('Communications equipment damaged.'), 'degraded');
assert.equal(presentation.physicalState('damaged or destroyed; final state unresolved'), 'degraded');
assert.equal(presentation.physicalState('No whole-site shutdown reported'), 'neutral');
console.log('presentation: v1.3.3 public evidence and physical-state semantics passed');
